<!-- Pleace this snippet right after opening the head tag to make it work properly -->

<!-- This code is licensed under GNU GPL v3 -->
<!-- You are allowed to freely copy, distribute and use this code, but removing author credit is strictly prohibited -->
<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->

<!-- REDIRECTING STARTS -->
<link rel="canonical" href="https://ovinee.wixsite.com/n2sl"/>
<noscript>
	<meta http-equiv="refresh" content="0;URL=https://ovinee.wixsite.com/n2sl">
</noscript>
<!--[if lt IE 9]><script type="text/javascript">var IE_fix=true;</script><![endif]-->
<script type="text/javascript">
	var url = "https://ovinee.wixsite.com/n2sl";
	if(typeof IE_fix != "undefined") // IE8 and lower fix to pass the http referer
	{
		document.write("redirecting..."); // Don't remove this line or appendChild() will fail because it is called before document.onload to make the redirect as fast as possible. Nobody will see this text, it is only a tech fix.
		var referLink = document.createElement("a");
		referLink.href = url;
		document.body.appendChild(referLink);
		referLink.click();
	}
	else { window.location.replace(url); } // All other browsers
</script>
<!-- Credit goes to http://insider.zone/ -->
<!-- REDIRECTING ENDS -->
<!--
---
title: ""
feature_text: ""
feature_image: "https://unsplash.it/1300/400?image=1040"
excerpt: ""
---

### About Youngbin Im
__*I'm looking for motivated undergraduate/graduate students who are interested in networks and systems. Please drop me an email if you want to work with me.*__

I joined the School of Electrical and Computer Engineering at Ulsan National Institute of Science and Technology (UNIST) in September 2019.

My research mainly focuses on the theory and algorithm based practical system implementation, and deployment. I have been actively working on a datacenter memory disaggregation system, a new TCP latency measurement solution, practical mobile data offloading systems, caching strategies for the next generation Internet such as Named Data Networking (NDN), innovative adaptive video streaming solutions, and wireless networks and security. 

I received my B.S. and Ph.D. degrees in Computer Science and Engineering from Seoul National University in 2006 and 2014, respectively. During my graduate program, I was a visiting student at Princeton University. Before joining UNIST, I was a postdoctoral researcher in the Department of Computer Science at University of Colorado Boulder from 2015 to 2019.

My e-mail address is ybim AT unist DOT ac DOT kr
-->
